include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/helloworld:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

mpi4py 1 node:
  stage: test
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - hostname
    - /opt/venv/bin/python3 /opt/repo/test.py
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 4
    SLURM_LABELIO: 1

mpi4py 2 node:
  stage: test
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - hostname
    - /opt/venv/bin/python3 /opt/repo/test.py
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 4
    SLURM_LABELIO: 1

osu_bw 1 node:
  stage: test
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - /usr/local/bin/osu_bw D D
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 2

osu_bw 2 node:
  stage: test
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - /usr/local/bin/osu_bw D D
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 2
